config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("survey_q.urls")),
    path("user/", include("user.urls")),
    path("survey/", include("survey_a.urls")),
]

survey_a/urls.py
from django.urls import path
from survey_a import views


app_name = "survey_a"

urlpatterns = [
    path("detail/<int:pk>", views.send_survey_detail, name="detail"),
]

survey_q/urls.py
from django.urls import path
from survey_q import views


app_name = "survey_q"

urlpatterns = [
    path("", views.survey_create, name="create"),
    path("list", views.survey_list, name="list"),
    path("update/<int:pk>", views.survey_update, name="update"),
    path("delete/<int:pk>", views.survey_delete, name="delete"),
    path("information/<int:pk>", views.survey_information, name="info"),
]

user/urls.py
from django.urls import path
from user import views


app_name = "user"

urlpatterns = [
    path("login", views.admin_page_login, name="login"),
    path("logout", views.admin_page_logout, name="logout"),
]

survey_a/models.py
from django.db import models
from survey_q.models import Question, Choice
from django.core.validators import RegexValidator


# 사용자 모델 Participant, Answer
class Participant(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    phoneNumberRegex = RegexValidator(regex = r'^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$') # 전화번호 필드 유효성검사
    phone = models.CharField(validators = [phoneNumberRegex], max_length = 16, verbose_name="작성자 전화번호")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="생성 날짜")

class Answer(models.Model):
    participant = models.ForeignKey(Participant, on_delete=models.CASCADE, verbose_name="설문 작성자")
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE, verbose_name="설문 질문 항목")
    num = models.IntegerField(verbose_name="설문 질문 응답")

survey_q/models.py
from django.db import models
from django.contrib.auth import get_user_model

Manager = get_user_model() # app 증가할 경우 settins.py에 명시


# 관리자 모델 Question, Choice
class Question(models.Model):
    # 담당자 delete 되어도 설문 정보는 남아있도록 on_delete=models.SET_NULL
    writer = models.ForeignKey(Manager, null=True, on_delete=models.SET_NULL, verbose_name="작성자")
    title = models.CharField(max_length=100, verbose_name="설문지 제목")
    notice = models.TextField(blank=True, null=True, verbose_name="설문지 설명")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="생성 날짜")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="최종 수정 날짜")

# Question 모델과 OneToOne 관계, 세부항목 추가 모델
class Choice(models.Model):
    CATEGORY_CHOICE = (
        ('checkbox', 'checkbox'),
        ('radio', 'radio'),
        ('select', 'select'),
    )
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    category = models.CharField(max_length=10, choices=CATEGORY_CHOICE, default='checkbox', verbose_name="유형 선택")
    choice_title = models.CharField(max_length=100, verbose_name="질문")
    item1 = models.CharField(max_length=100, verbose_name="옵션")
    item2 = models.CharField(max_length=100, blank=True, null=True, verbose_name="옵션")
    item3 = models.CharField(max_length=100, blank=True, null=True, verbose_name="옵션")
    item4 = models.CharField(max_length=100, blank=True, null=True, verbose_name="옵션")
    item5 = models.CharField(max_length=100, blank=True, null=True, verbose_name="옵션")
    item6 = models.CharField(max_length=100, blank=True, null=True, verbose_name="옵션")

user/models.py
from django.db import models

# Create your models here.

survey_q/forms.py
from django import forms
from survey_q.models import Question, Choice


class QuestionUpdateForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["title", "notice"]

class ChoiceUpdateForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ["category", "choice_title", "item1","item2","item3","item4","item5","item6"]

survey_a/views.py
from django.shortcuts import render, redirect
from survey_q.models import Question, Choice
from survey_a.models import Participant, Answer

# Create your views here.
def send_survey_detail(request, pk):
    if request.method == 'GET':
        survey = Question.objects.filter(id=pk)
        return render(request, "survey_q/survey_detail.html", { 'survey': survey })

# (추가) 사용자 설문지 작성 후 정보 저장 기능

survey_q/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from survey_q.models import Question, Choice
from survey_q.forms import QuestionUpdateForm, ChoiceUpdateForm


# Create your views here.
@login_required(login_url='user:login')
def survey_create(request):
    writer = request.user.id
    if request.method == 'GET':
        return render(request, "survey_q/survey_create.html")
    elif request.method == 'POST':
        title = request.POST.get("title", None)
        notice = request.POST.get("notice", None)
        choice_title = request.POST.get("choice_title", None)
        category = request.POST.get("category", None)
        item1 = request.POST.get("item1", None)
        item2 = request.POST.get("item2", None)
        item3 = request.POST.get("item3", None)
        item4 = request.POST.get("item4", None)
        item5 = request.POST.get("item5", None)
        item6 = request.POST.get("item6", None)

        question = Question.objects.create(writer_id=writer, title=title, notice=notice)
        Choice.objects.create(question_id=question.id, choice_title=choice_title, category=category, item1=item1, item2=item2, item3=item3, item4=item4, item5=item5, item6=item6)

        return redirect("survey_a:detail", question.id)


@login_required(login_url='user:login')
def survey_list(request):
    if request.method == 'GET':
        SurveyList = Question.objects.all().order_by('-id')
        return render(request, "survey_q/survey_list.html", { 'list': SurveyList })
    elif request.method == 'POST':
        return redirect("survey_q:create")


@login_required(login_url='user:login')
def survey_information(request, pk):
    if request.method == 'GET':
        survey = Question.objects.filter(id=pk)
        return render(request, "survey_q/survey_info.html", { 'survey': survey })


@login_required(login_url='user:login')
def survey_update(request, pk):
    question = Question.objects.get(id=pk)
    # choice = Choice.objects.filter(question_id=pk) # Question 연결된 Choice는 다중이라 오류 발생
    if request.method == 'POST':
        form1 = QuestionUpdateForm(request.POST)
        # form2 = ChoiceUpdateForm(request.POST)
        if form1.is_valid():
            question.title = request.POST["title"]
            question.notice = request.POST["notice"]
            question.save()
        # if form2.is_valid():
        #     choice.category = request.POST["category"]
        #     choice.choice_title = request.POST["choice_title"]
        #     choice.item1 = request.POST["item1"]
        #     choice.item2 = request.POST["item2"]
        #     choice.item3 = request.POST["item3"]
        #     choice.item4 = request.POST["item4"]
        #     choice.item5 = request.POST["item5"]
        #     choice.item6 = request.POST["item6"]
        #     choice.save()
        return redirect("survey_a:detail", pk=pk)
    elif request.method == 'GET':
        questionD = QuestionUpdateForm(instance = question)
        context1 = {"question": questionD}
        # choiceD = ChoiceUpdateForm(instance = choice.id)
        # context2 = {"choice": choiceD}
        return render(request, "survey_q/survey_update.html", context1)


@login_required(login_url='user:login')
def survey_delete(request, pk):
    Question.objects.filter(id=pk).delete()
    return redirect("survey_q:list")

user/views.py
from django.contrib import auth
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required


# Create your views here.
def admin_page_login(request):
    if request.method == 'GET':
        # 사용자 로그인 확인
        if request.user.is_authenticated:
            return redirect("survey_q:create")
        else: return render(request, "login.html")

    elif request.method == 'POST':
        username = request.POST.get("id", None)
        password = request.POST.get("password", None)

        true_user = auth.authenticate(request, username=username, password=password)
        if true_user is not None:
            auth.login(request, true_user)
            return redirect("survey_q:create")
        else:
            return render(request, "login.html", {"error": "ID 또는 password 확인해 주세요!"})
    else:
        return redirect("survey_q:create")


@login_required
def admin_page_logout(request):
    auth.logout(request)
    return redirect("user:login")

templates/login.html
{% extends 'main_nav.html' %}
{% load static %}
{% block title %} survey create {% endblock %}

{% block style %}
    <link href="/static/css/login.css" rel="stylesheet" type="text/css">
{% endblock %}

<!--content-->
{% block content %}
    <div class="login-page">
        <div class="form">
        <form class="login-form" method="post" action="{% url 'user:login' %}">
            {% csrf_token %}
            <h3>Admin Page Login</h3>
            <input type="text" placeholder="admin ID" name="id">
            <input type="password" placeholder="password" name="password">
            {% if error %}
                <p style="color: darkred">{{ error }}</p>
            {% endif %}
            <button type="submit">login</button>
        </form>
        </div>
    </div>

    <!-- <script defer src="/static/js/login.js"></script> -->
{% endblock content %}

templates/main_nav.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link href="/static/css/main_nav.css" rel="stylesheet" type="text/css">

    {% block style %}
    {% endblock %}
</head>

<body>
    <nav id="nav">
        <a class="link" href="#">Survey Logo</a>
    </nav>
    <nav id="nav">
        <a class="link-1" href="{% url 'survey_q:list' %}">survey list</a>
        <a class="link-1" href="{% url 'survey_q:create' %}">survey create</a>
        {% if user.is_authenticated %}
            <a class="link-1" href="{% url 'user:logout' %}">logout</a>
        {% else %}
            <a class="link-1" href="{% url 'user:login' %}">admin login</a>
        {% endif %}
    </nav>


    {% block content %}
    {% endblock %}
</body>

</html>

templates/survey_q/survey_create.html
{% extends 'main_nav.html' %}
{% load static %}
{% block title %} survey create {% endblock %}

{% block style %}
    <link href="/static/css/survey_create.css" rel="stylesheet" type="text/css">
{% endblock %}

<!--content-->
{% block content %}
    <div class="survey-create">
        <div class="form">
        <form class="survey-form" method="post" action="{% url 'survey_q:create' %}">
            {% csrf_token %}
            <h3>Survey Title</h3>
            <input type="text" placeholder="설문지 제목" name="title">
            <input type="text" placeholder="설문지 설명" name="notice">
            <button type="submit">complete</button>
        <!-- </form> -->
        </div>
    </div>

    <div class="survey-create">
        <div class="form">
        <!-- <form class="survey-form" method="post" action="{% url 'survey_q:create' %}"> -->
            <!-- {% csrf_token %} -->
            <h3>Survey Question</h3>

            <label for="pet-select">choose a option:</label>
            <select name="category">
                <!-- <option value="">--Please choose an option--</option> -->
                <option value="checkbox">Checkbox</option>
                <option value="radio">Radio</option>
                <option value="select">Select</option>
            </select>

            <input type="text" placeholder="질문 (필수 입력)" name="choice_title">
            <input type="text" placeholder="옵션1 (필수 입력)" name="item1">
            <input type="text" placeholder="옵션2 (필수 입력)" name="item2">
            <input type="text" placeholder="옵션3" name="item3">
            <input type="text" placeholder="옵션4" name="item4">
            <input type="text" placeholder="옵션5" name="item5">
            <input type="text" placeholder="옵션6 (최대6개)" name="item6">
        </form>
        </div>
    </div>
    <!-- 추가 질문 항목  -->
    <!-- <div class="question-option"></div>

    <footer>
        <a class="link-2" onclick="">Add Question</a>
        <a class="link-2" type="submit">Complete !!</a>
    </footer> -->



    <!-- <script defer src="/static/js/survey_create.js"></script> -->
{% endblock content %}

templates/survey_q/survey_detail.html
{% extends 'main_nav.html' %}
{% load static %}
{% block title %} survey detail {% endblock %}

{% block style %}
    <link href="/static/css/survey_detail.css" rel="stylesheet" type="text/css">
{% endblock %}

<!--content-->
{% block content %}
    {% for survey in survey %}
    <div class="survey-detail">
        <div class="form">
        <form class="survey-form">
            <h2>{{survey.title}}</h2>
            <div>{{survey.notice}}</div>
        </form>
        </div>
    </div>

        <div class="survey-detail">
            <div class="forms">
            {% for choice in survey.choice_set.all %}
            <form class="survey-form" method="post" action="#">
                {% csrf_token %}
                <h3>{{ forloop.counter }}. {{choice.choice_title}}</h3>
                <label><input type={{choice.category}} name="num" value="1">{{choice.item1}}</label><br>
                <label><input type={{choice.category}} name="num" value="2">{{choice.item2}}</label><br>
                <label><input type={{choice.category}} name="num" value="3">{{choice.item3}}</label><br>
                <label><input type={{choice.category}} name="num" value="4">{{choice.item4}}</label><br>
                <label><input type={{choice.category}} name="num" value="5">{{choice.item5}}</label><br>
                <label><input type={{choice.category}} name="num" value="6">{{choice.item6}}</label><br>
            {% endfor %}
            </form>
            </div>
        </div>
    {% endfor %}
    <div class="survey-detail" style="margin-bottom: 200px;">
        <div class="form">
            <form class="survey-form" method="post" action="#">
                {% csrf_token %}
                <h3>설문해 주셔서 감사합니다. 작성자의 [전화번호]를 입력해 주세요.</h3>
                <input type="text" placeholder="전화번호 입력 예시 : 010-0000-0000" name="phone">
                
                <button type="submit" style="width: 70%; min-width: 250px;">설문 작성 완료하기</button>
            </form>
            </div>
        </div>
    </div>

    <!-- <script defer src="/static/js/survey_detail.js"></script> -->
{% endblock content %}

templates/survey_q/survey_info.html
{% extends 'main_nav.html' %}
{% load static %}
{% block title %} survey information {% endblock %}

{% block style %}
    <link href="/static/css/survey_info.css" rel="stylesheet" type="text/css">
{% endblock %}

<!--content-->
{% block content %}
    {% if survey %}
        {% for data in survey %}
        <div class="survey-info">
            <div class="form">
            <form class="survey-form">
                <div>작성자 : {{ data.writer }}</div>
                <div>설문 제목: {{ data.title }}</div>
                <div>설문 설명: {{ data.notice }}</div>
                <div>문항 수: {{ data.choice_set.all.count }}</div>
                <div>참여 수: {{ data.participant_set.all.count }}</div>
                <div>생성일: {{ data.created_at|date:'Y-m-d' }}</div>
                <div>수정일: {{ data.updated_at|date:'Y-m-d' }}</div>
                <div class="btn-list" style="text-align: center; margin-top: 24px;">
                    <a href="{% url 'survey_a:detail' data.id %}">미리보기</a>
                    <a href="{% url 'survey_q:update' data.id %}">수정하기</a>
                </div>
            </form>
            </div>
        </div>

        <div class="content">
            <table class="board">
                <thead>
                    <tr class="header">
                        <th style="width:20%;">질문</th>
                        <th style="width:60%;">문항</th>
                        <th style="width:10%;">응답수</th>
                        <th style="width:10%;">응답비율</th>
                    </tr>
                </thead>
                <tbody>
                    {% for choice in data.choice_set.all %}
                    <tr class="even_bgcolor">
                        <td>{{ choice.choice_title }}</td>
                        <td>{{ choice.item1}}</td>
                        <td>{{ choice.answer_set.all.count }}</td>
                        <td>응답비율</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endfor %}
    {% endif %}
    
    <div class="csv">
        <button>CSV 다운받기</button>
    </div>

    <!-- <script defer src="/static/js/survey_info.js"></script> -->
{% endblock content %}

templates/survey_q/survey_list.html
{% extends 'main_nav.html' %}
{% load static %}
{% block title %} survey list {% endblock %}

{% block style %}
    <link href="/static/css/survey_list.css" rel="stylesheet" type="text/css">
{% endblock %}

<!--content-->
{% block content %}
    <div class="content">
        <table class="board">
            <thead>
                <tr class="header">
                    <th style="width:10%;">순번</th>
                    <th style="width:30%">제목</th>
                    <th style="width:10%">문항</th>
                    <th style="width:10%">응답</th>
                    <th style="width:10%">작성자</th>
                    <th style="width:15%">작성일자</th>
                    <th style="width:15%">작업버튼</th>
                </tr>
            </thead>
            <tbody>
            {% if list %}
                {% for data in list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>
                        <a href="{% url 'survey_q:info' data.id %}">
                            {{ data.title }}
                        </a>
                    </td>
                    <td>{{ data.choice_set.all.count }}</td>
                    <td>{{ data.participant_set.all.count }}</td>
                    <td>{{ data.writer }}</td>
                    <td>{{ data.created_at|date:'Y-m-d' }}</td>
                    <td><div class="btn-list" style="text-align: center;">
                        <input type="text" id="text{{data.id}}" value="http://127.0.0.1:8000/survey/detail/{{data.id}}" style="display: none;">
                        <input type="button" onclick="fn_final( '{{data.id}}' )" value="링크"/>
                        <a href="{% url 'survey_q:update' data.id %}">수정</a>
                        <a style="background-color: brown;" href="{% url 'survey_q:delete' data.id %}" onclick="return delchk();">삭제</a>
                    </div></td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td>작성된 게시글이 없습니다.</td>
                </tr>
            {% endif %}
            </tbody>
        </table>
    </div>

    <script defer src="/static/js/survey_list.js"></script>
{% endblock content %}

templates/survey_q/survey_update.html
{% extends 'main_nav.html' %}
{% load static %}
{% block title %} survey edit {% endblock %}

{% block style %}
    <link href="/static/css/survey_update.css" rel="stylesheet" type="text/css">
{% endblock %}

<!--content-->
{% block content %}
    <div class="survey-update">
        <div class="form">
            <form action="" method="POST">
                {% csrf_token %}
                <div>
                    {{ question }}
                    <button type="submit">수정</button>
                </div>
            </form>
        </div>
    </div>
    <!-- <script defer src="/static/js/survey_update.js"></script> -->
{% endblock content %}